### ISSUE TITLE
How to view URDF files in RViz or Gazebo?

### ISSUE THREAD

**Issue by dhruvsasuke** [pollen-robotics/reachy#9]
I have been trying to visualise the URDF files using RViz and Gazebo, but it seems that the meshes are incompatible with RViz and Gazebo. The URDF was parsed correctly since the transformation axes were visible in RViz but, the meshes were unable to load. Similarly in Gazebo, the model was successfully imported (shown in the left pane under models) but nothing was visible. 

![image](https://user-images.githubusercontent.com/35889082/71449774-5ee85800-277a-11ea-8910-89925c07607c.png)
                             Above image shows the errors in loading the RobotModel

![image](https://user-images.githubusercontent.com/35889082/71449779-70316480-277a-11ea-9f8c-39d2de96e66b.png)
                             As we can see, the TF has been loaded correctly

![image](https://user-images.githubusercontent.com/35889082/71449803-0a91a800-277b-11ea-99a4-14952648f42a.png)
                              Terminal window showing successful model spawn in Gazebo

![image](https://user-images.githubusercontent.com/35889082/71449797-eafa7f80-277a-11ea-9273-b1c00a15dd3f.png)
      Gazebo window after loading the model. The left pane shows reachy_robot but nothing is visible

**Comment by pierre-rouanet** [comment]
Fixed by 2d15a66c73b5546b03c92bdddcc8445785e6cc04 and https://github.com/pollen-robotics/orbita/commit/4aad18a4cf33611c84877c56ee2567e22c853e68
